### ISSUE TITLE
Does not work with Alfred 3?

### ISSUE THREAD

**Issue by Soben** [gampleman/alfred-find-my-iphone#1]
Maybe I am just installing this incorrectly, but you do not list how to convert your git repo into an actual uploadable alfred workflow.

When I start typing "Find my", it shows up, by when I continue on to authenticate, it disappears and only shows the search-based results...

![screen shot 2016-06-10 at 11 48 32 am](https://cloud.githubusercontent.com/assets/194854/15970378/4ab9d634-2f02-11e6-9fbf-fba9bfb97363.png)

![screen shot 2016-06-10 at 11 48 42 am](https://cloud.githubusercontent.com/assets/194854/15970384/5020f24c-2f02-11e6-8bc3-41687cccb138.png)

Even if I change the query term to be something simpler, and even require an argument, it makes no difference... 

![screen shot 2016-06-10 at 11 57 26 am](https://cloud.githubusercontent.com/assets/194854/15970437/907e95d8-2f02-11e6-830b-4ff7c5d7cdf7.png)

Coworker and I were noticing this repo today, and we were excited to try it out, but these barriers are getting in the way. :)

**Comment by danyim** [comment]
+1. Excited to use this workflow also, but it fails on Alfred 3

**Comment by danyim** [comment]
Here's what I see when I debug the workflow:

```
Starting debug for 'Find my iPhone'

[2017-01-22 13:24:04][ERROR: input.scriptfilter] Code 1: Ignoring bcrypt-3.1.10 because its extensions are not built.  Try: gem pristine bcrypt --version 3.1.10
Ignoring binding_of_caller-0.7.2 because its extensions are not built.  Try: gem pristine binding_of_caller --version 0.7.2
Ignoring curb-0.9.3 because its extensions are not built.  Try: gem pristine curb --version 0.9.3
Ignoring debug_inspector-0.0.2 because its extensions are not built.  Try: gem pristine debug_inspector --version 0.0.2
Ignoring eventmachine-1.0.7 because its extensions are not built.  Try: gem pristine eventmachine --version 1.0.7
Ignoring ffi-1.9.10 because its extensions are not built.  Try: gem pristine ffi --version 1.9.10
Ignoring ffi-1.9.6 because its extensions are not built.  Try: gem pristine ffi --version 1.9.6
Ignoring ffi-1.9.3 because its extensions are not built.  Try: gem pristine ffi --version 1.9.3
Ignoring hitimes-1.2.2 because its extensions are not built.  Try: gem pristine hitimes --version 1.2.2
Ignoring hpricot-0.8.6 because its extensions are not built.  Try: gem pristine hpricot --version 0.8.6
Ignoring http_parser.rb-0.6.0 because its extensions are not built.  Try: gem pristine http_parser.rb --version 0.6.0
Ignoring json-1.8.3 because its extensions are not built.  Try: gem pristine json --version 1.8.3
Ignoring kgio-2.9.3 because its extensions are not built.  Try: gem pristine kgio --version 2.9.3
Ignoring mysql2-0.4.2 because its extensions are not built.  Try: gem pristine mysql2 --version 0.4.2
Ignoring mysql2-0.3.16 because its extensions are not built.  Try: gem pristine mysql2 --version 0.3.16
Ignoring nokogiri-1.6.7.2 because its extensions are not built.  Try: gem pristine nokogiri --version 1.6.7.2
Ignoring raindrops-0.13.0 because its extensions are not built.  Try: gem pristine raindrops --version 0.13.0
Ignoring sass-3.3.0 because its extensions are not built.  Try: gem pristine sass --version 3.3.0
Ignoring string-scrub-0.0.5 because its extensions are not built.  Try: gem pristine string-scrub --version 0.0.5
Ignoring therubyracer-0.12.2 because its extensions are not built.  Try: gem pristine therubyracer --version 0.12.2
Ignoring unf_ext-0.0.7.1 because its extensions are not built.  Try: gem pristine unf_ext --version 0.0.7.1
Ignoring unicorn-4.9.0 because its extensions are not built.  Try: gem pristine unicorn --version 4.9.0
/Users/User/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.99BA7B21-2CE9-463C-BBEE-FD60BC26ADB0/bundle/ruby/2.0.0/gems/ffi-1.9.10/lib/ffi/library.rb:133:in `block in ffi_lib': Could not open library 'c': dlopen(c, 5): image not found. (LoadError)
Could not open library 'libc.dylib': dlopen(libc.dylib, 5): image not found
  from /Users/User/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.99BA7B21-2CE9-463C-BBEE-FD60BC26ADB0/bundle/ruby/2.0.0/gems/ffi-1.9.10/lib/ffi/library.rb:100:in `map'
  from /Users/User/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.99BA7B21-2CE9-463C-BBEE-FD60BC26ADB0/bundle/ruby/2.0.0/gems/ffi-1.9.10/lib/ffi/library.rb:100:in `ffi_lib'
  from /Users/User/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.99BA7B21-2CE9-463C-BBEE-FD60BC26ADB0/bundle/ruby/2.0.0/gems/ethon-0.7.4/lib/ethon/libc.rb:8:in `<module:Libc>'
  from /Users/User/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.99BA7B21-2CE9-463C-BBEE-FD60BC26ADB0/bundle/ruby/2.0.0/gems/ethon-0.7.4/lib/ethon/libc.rb:6:in `<module:Ethon>'
  from /Users/User/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.99BA7B21-2CE9-463C-BBEE-FD60BC26ADB0/bundle/ruby/2.0.0/gems/ethon-0.7.4/lib/ethon/libc.rb:1:in `<top (required)>'
  from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /Users/User/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.99BA7B21-2CE9-463C-BBEE-FD60BC26ADB0/bundle/ruby/2.0.0/gems/ethon-0.7.4/lib/ethon.rb:10:in `<top (required)>'
  from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /Users/User/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.99BA7B21-2CE9-463C-BBEE-FD60BC26ADB0/bundle/ruby/2.0.0/gems/typhoeus-0.7.3/lib/typhoeus.rb:2:in `<top (required)>'
  from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /Users/User/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.99BA7B21-2CE9-463C-BBEE-FD60BC26ADB0/locator.rb:6:in `<top (required)>'
  from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from ./main.rb:8:in `<main>'
```

**Comment by Tapppi** [comment]
Hey, basically ruby (and openssl :D) is fucked on new macOS installations it seems. Pretty simple fix if you are in the dev know how:
```bash
# Install openssl and rvm
brew install openssl
\curl -sSL https://get.rvm.io | bash -s stable

# Install ruby
rvm install 2.4.1 --with-openssl-dir=`brew --prefix openssl`

# Install bundler
gem install bundler

# In workflow dir (to get there right click workflow and select "Open Terminal" in Alfred):
bundler install --path bundle

# Replace all the ruby invocations in workflow actions with:
~/.rvm/rubies/ruby-2.4.1/bin/ruby
# For example in the script filter:
~/.rvm/rubies/ruby-2.4.1/bin/ruby ./main.rb "{query}"
```

Could probably somehow generalise this into a new simple installation, but too lazy, this works 😂

**Comment by alanhe421** [comment]
## error on Catalina 10.15.7

![image](https://user-images.githubusercontent.com/9245110/107841121-1dd65b80-6df3-11eb-8f03-1cd608caaa1e.png)


so old code, When there is a demand, I give up. If there is a strong demand in the future, I will dev one.

The principle is actually to use the web version of find my.

**Comment by alanhe421** [comment]
I developed one.

Support alfred4.

https://github.com/alanhg/alfred-workflows/tree/master/find-my-iphone
